### ISSUE TITLE
Introducing GeoStats.jl

### ISSUE THREAD

**Issue by juliohm** [dchudz/SpatialStats.jl#2]
Hi @dchudz,

I've just found your package. If you are working with spatial statistics, please consider joining efforts in GeoStats.jl. We have many algorithms already implemented there, and many more will be available soon in future releases: https://github.com/juliohm/GeoStats.jl

If you feel like contributing to the project, please consider adding a reference to it in your README. That way we can attract more spatial statisticians together.

Sincerely,

**Comment by dchudz** [comment]
Cool, thanks! I hope I get some time to help out. (As you can see I haven't had much chance to work on this package...)

**Comment by juliohm** [comment]
Awesome! If you can, give a star to the project or add it to the README for others to join. :blush:

Closing the issue.
